### PR TITLE
Implement drain functionality, initial untested commit, DRAFT ONLY

### PR DESCRIPTION
**Pull request by jsudano**
Details at https://github.com/nats-io/nats.rs/issues/1325

### CODE REVIEW

**Comment by Jarema** [comment]
Hey.
Just to give you early feedback - I think it looks well.
Obviously requires quite a lot of testing.

**Comment by jsudano** [comment]
Awesome thank you, I'll get to writing tests then! 

Is there a "development" doc for the repo? I've gathered that I need to manually run a NATS server locally before running `cargo test`, but I see test failures related to "no such file or directory" (even on master) when trying to run tests against that local NATS server. I'm assuming there's some setup step I'm missing.

**Comment by Jarema** [comment]
All you need to do is having `nats-server` available in you `PATH`.
The test suite will drive starting, cleaning up and shutting down the server.

**Comment by jsudano** [comment]
@Jarema thanks, that got me up and running! 

Now that I have some tests I will move this to a PR against the main repo to keep discussion in the relevant place

**Pull request closed without merging**
